import {
  db,
  categoriesTable,
  postsTable,
  resourcesTable,
} from "@workspace/db";
import { logger } from "./lib/logger";

const categories = [
  {
    slug: "ai-tools",
    name: "AI Tools",
    description: "Hand-picked AI tools that pay for themselves — from writing copilots to autonomous agents.",
    color: "#7C3AED",
    icon: "Wand2",
  },
  {
    slug: "side-hustles",
    name: "AI Side Hustles",
    description: "Realistic, weekend-sized hustles you can spin up with AI as the unfair advantage.",
    color: "#F59E0B",
    icon: "Rocket",
  },
  {
    slug: "freelancing",
    name: "Freelancing",
    description: "How to land clients, scope AI-augmented work, and price for outcomes — not hours.",
    color: "#10B981",
    icon: "Briefcase",
  },
  {
    slug: "automation",
    name: "Automation",
    description: "No-code and low-code workflows that quietly print money while you sleep.",
    color: "#0EA5E9",
    icon: "Workflow",
  },
  {
    slug: "passive-income",
    name: "Passive Income",
    description: "Build digital assets — courses, templates, agents — that compound over time.",
    color: "#EC4899",
    icon: "TrendingUp",
  },
  {
    slug: "guides",
    name: "Guides",
    description: "Long-form playbooks that walk you through real, end-to-end builds.",
    color: "#EF4444",
    icon: "BookOpen",
  },
];

const author1 = {
  name: "Maya Chen",
  role: "Editor in Chief",
  avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=maya&backgroundColor=fde68a",
};
const author2 = {
  name: "Jordan Reyes",
  role: "Senior Writer",
  avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jordan&backgroundColor=c4b5fd",
};
const author3 = {
  name: "Priya Anand",
  role: "Automation Lead",
  avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya&backgroundColor=a7f3d0",
};
const author4 = {
  name: "Sam Okafor",
  role: "Contributing Writer",
  avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sam&backgroundColor=fecaca",
};

function cover(seed: string) {
  return `https://picsum.photos/seed/${encodeURIComponent(seed)}/1200/700`;
}

const md = (parts: string[]) => parts.join("\n\n");

const posts = [
  {
    slug: "ai-side-hustles-2026",
    categorySlug: "side-hustles",
    title: "12 AI Side Hustles That Actually Made Money in 2026",
    excerpt:
      "We tracked 200 indie operators for six months. These twelve hustles consistently produced real income — and the patterns behind them are easier to copy than you'd think.",
    difficulty: "beginner",
    incomeType: "active",
    tags: ["side-hustle", "trends", "indie", "case-study"],
    premium: false,
    featured: true,
    readMinutes: 9,
    views: 14820,
    likes: 612,
    author: author1,
    content: md([
      "## The shape of an AI hustle that works",
      "Most hustles fail not because the AI is bad, but because the offer is fuzzy. The winners have a sharp service description, a single channel they show up on every day, and a price anchored to the outcome — not to the time spent.",
      "## What we measured",
      "We tracked monthly net revenue, hours per week, and churn for 200 operators between January and June 2026. The twelve hustles below all cleared $1,500/mo on under 10 hours per week.",
      "## The twelve hustles",
      "- **AI-edited podcast clips** — turn long episodes into vertical short-form for creators who can't be bothered.",
      "- **SEO programmatic landing pages** — local services, niche directories, comparison hubs.",
      "- **Cold email infrastructure as a service** — set up, warm up, and maintain inboxes for B2B founders.",
      "- **AI-narrated audiobooks** — public domain + a clean narration pipeline.",
      "- **Niche newsletters** — micro-audience, sponsorships, no ads.",
      "- **Notion templates with embedded GPT** — sell the system, not the doc.",
      "- **Faceless YouTube channels** — script + b-roll + voice, batched weekly.",
      "- **AI-assisted resume rewrites** — premium price, 24h turnaround.",
      "- **Etsy print-on-demand with AI art** — niche down ruthlessly.",
      "- **Local business automation** — booking, replies, reviews.",
      "- **Custom GPT agencies** — small teams of agents for ops-heavy SMBs.",
      "- **Stock prompt libraries** — sell the prompt, not the platform.",
      "## The patterns",
      "Repeatability beats novelty. A boring service done weekly compounds; a clever experiment done once does not.",
    ]),
  },
  {
    slug: "build-faceless-youtube-channel",
    categorySlug: "passive-income",
    title: "Build a Faceless YouTube Channel With AI in a Weekend",
    excerpt:
      "A practical, end-to-end pipeline for scripting, voicing, editing, and shipping faceless videos that don't look like every other AI channel.",
    difficulty: "intermediate",
    incomeType: "passive",
    tags: ["youtube", "faceless", "passive", "video"],
    premium: false,
    featured: true,
    readMinutes: 14,
    views: 9412,
    likes: 421,
    author: author2,
    content: md([
      "## Why most AI channels look the same",
      "Same stock footage, same robotic narration, same bullet-point scripts. The audience pattern-matches in three seconds and bounces. The fix is taste, not tools.",
      "## The pipeline",
      "- **Niche pick** — pick a niche where you can hold a real opinion.",
      "- **Script** — write the first three videos by hand. Use AI only to compress.",
      "- **Voice** — invest in a good TTS voice and a custom intonation guide.",
      "- **Visuals** — mix stock, AI-generated b-roll, and motion graphics in a 60/30/10 ratio.",
      "- **Cut** — let the script breathe. Two-second silences are fine.",
      "## What you can realistically expect",
      "Three months in, expect 1,000 subs and ~$50/mo from RPM if your niche is small. The win is the asset library you build along the way.",
    ]),
  },
  {
    slug: "freelance-with-ai-how-to-charge",
    categorySlug: "freelancing",
    title: "How To Charge When AI Does 80% Of The Work",
    excerpt:
      "Hourly billing is dead the moment your tools are 10x faster. Here's the pricing model that aligns your incentives with your client's outcome — and pays you for taste.",
    difficulty: "intermediate",
    incomeType: "active",
    tags: ["pricing", "freelance", "consulting", "ops"],
    premium: false,
    featured: false,
    readMinutes: 8,
    views: 7301,
    likes: 312,
    author: author2,
    content: md([
      "## The hourly trap",
      "If you bill by the hour, every productivity gain is a pay cut. The ceiling is your awake time, and AI just made you faster.",
      "## Outcome packages",
      "Sell a result. Three tiers, fixed scope, fixed price. Discovery call → audit → execution. Your job becomes scoping accurately, not typing fast.",
      "## What outcome to sell",
      "- A landing page that converts above an agreed baseline.",
      "- A backlog of 20 SEO articles, indexed.",
      "- A working agent that handles support tickets under 30 seconds, escalating cleanly.",
    ]),
  },
  {
    slug: "no-code-automation-stack",
    categorySlug: "automation",
    title: "The No-Code AI Automation Stack We Actually Use",
    excerpt:
      "After two years of churn, here's the unsexy stack of seven tools we trust to glue together client workflows that survive the weekend.",
    difficulty: "beginner",
    incomeType: "hybrid",
    tags: ["automation", "no-code", "stack", "tools"],
    premium: false,
    featured: true,
    readMinutes: 11,
    views: 11203,
    likes: 488,
    author: author3,
    content: md([
      "## The stack",
      "- **n8n** for the spine — self-hostable, predictable.",
      "- **Make** for visual flows you'll hand off to a non-technical client.",
      "- **OpenAI + Anthropic** for the brains — never lock into one provider.",
      "- **Supabase** for the database when Airtable runs out of room.",
      "- **Resend** for transactional email.",
      "- **Vercel cron** for tiny scheduled tasks.",
      "- **Sentry** because something will break.",
      "## The principle",
      "Boring tools that compose well beat clever tools that lock you in. Optimize for the year-from-now version of you.",
    ]),
  },
  {
    slug: "ai-newsletter-blueprint",
    categorySlug: "passive-income",
    title: "The Tiny AI Newsletter Blueprint",
    excerpt:
      "300 subscribers. $4,000 a month. The math on micro-newsletters changed when AI made research cheap — here's how to ride that curve.",
    difficulty: "beginner",
    incomeType: "passive",
    tags: ["newsletter", "writing", "audience", "media"],
    premium: true,
    featured: false,
    readMinutes: 10,
    views: 5821,
    likes: 287,
    author: author1,
    content: md([
      "## Why micro now",
      "Sponsors finally figured out that 300 of the right people beat 30,000 of the wrong ones. Premium niches — VC, biotech ops, AI infra — pay $400+ per primary slot at small lists.",
      "## The cadence",
      "Weekly, every time. Same day. Three sections. One sponsor. Show up forever.",
      "## The research loop",
      "Use AI to summarize, never to write. Your voice is the asset. Your readers can smell template prose from the subject line.",
    ]),
  },
  {
    slug: "best-ai-writing-tools-2026",
    categorySlug: "ai-tools",
    title: "The 9 AI Writing Tools Worth Paying For in 2026",
    excerpt:
      "Most AI writing tools are wrappers. These nine earn their subscription because they solve a real workflow — and we use every one.",
    difficulty: "beginner",
    incomeType: "hybrid",
    tags: ["writing", "tools", "review", "subscription"],
    premium: false,
    featured: true,
    readMinutes: 12,
    views: 18922,
    likes: 803,
    author: author4,
    content: md([
      "## How we evaluated",
      "We used each tool on real client work for at least four weeks. Anything we kept paying for after the trial made the list.",
      "## The list",
      "- **Lex** — quiet writing surface with AI you only see when you ask.",
      "- **Type** — drafts long-form fast, especially with house-style memory.",
      "- **Cursor** — for technical writers, the cmd+K loop is unbeatable.",
      "- **Granola** — meeting notes that actually summarize what mattered.",
      "- **Reflect** — networked notes with a crisp daily review.",
      "- **Spiral** — repurposes one piece into eight formats without flattening voice.",
      "- **Wordtune** — the only line editor we trust.",
      "- **Hemingway 3** — strict mode is back, and the AI rewrites are tasteful.",
      "- **Substack Notes AI** — surprisingly useful for headline iteration.",
    ]),
  },
  {
    slug: "etsy-print-on-demand-niche-guide",
    categorySlug: "guides",
    title: "Etsy + AI Art: The Niching Guide That Makes The Math Work",
    excerpt:
      "Generic AI art prints don't sell. Hyper-specific designs for hyper-specific people do. Here is the niching framework we use to find one before you make a single mockup.",
    difficulty: "intermediate",
    incomeType: "passive",
    tags: ["etsy", "print-on-demand", "ecommerce", "niching"],
    premium: false,
    featured: false,
    readMinutes: 13,
    views: 6422,
    likes: 251,
    author: author4,
    content: md([
      "## The niching grid",
      "Audience x Identity x Occasion. Pick one cell. 'Wall art for new dads of twins on Father's Day' beats 'wall art' a thousand to one.",
      "## Mockups",
      "Use real-room mockups, not white backgrounds. The buyer needs to see it on their wall, not in a void.",
      "## Pricing",
      "Anchor at $34. Volume comes from listing breadth, not from chasing price.",
    ]),
  },
  {
    slug: "custom-gpt-agency-playbook",
    categorySlug: "ai-tools",
    title: "Starting a Custom GPT Agency In 30 Days",
    excerpt:
      "A four-week sprint from zero to your first paying client. Day-by-day plan, the offer, the cold outbound script, and what to charge.",
    difficulty: "advanced",
    incomeType: "active",
    tags: ["agency", "consulting", "gpts", "outbound"],
    premium: true,
    featured: false,
    readMinutes: 16,
    views: 4933,
    likes: 198,
    author: author3,
    content: md([
      "## Week 1 — pick a vertical",
      "Real estate, dental, accounting. Boring industries with painful workflows and budget. Pick one.",
      "## Week 2 — build a portfolio of three",
      "Build three sample agents nobody asked for. Public Loom for each.",
      "## Week 3 — outbound",
      "30 personalized cold emails per day. Reference one specific thing about the business.",
      "## Week 4 — close one",
      "Discovery call → scoped pilot → invoice. $2.5K starter, $1.2K/mo retainer.",
    ]),
  },
  {
    slug: "ai-resume-rewrites-business",
    categorySlug: "freelancing",
    title: "I Make $7K/Month Rewriting Resumes With AI",
    excerpt:
      "A first-person teardown of a hustle anyone can copy this weekend. The funnel, the price, the AI assist, and the exact prompts.",
    difficulty: "beginner",
    incomeType: "active",
    tags: ["resume", "case-study", "service", "income"],
    premium: false,
    featured: false,
    readMinutes: 7,
    views: 12044,
    likes: 537,
    author: author1,
    content: md([
      "## The funnel",
      "TikTok before/afters → free template → upsell to a $249 rewrite → optional $99 LinkedIn polish.",
      "## The AI assist",
      "Custom GPT for first-pass rewrites, then I edit by hand. The AI sets the structure; I bring the taste.",
      "## The numbers",
      "30 rewrites/mo on average. 90 minutes each. $7K cleared on a side hustle that fits between school pickups.",
    ]),
  },
  {
    slug: "automate-customer-support-agents",
    categorySlug: "automation",
    title: "Automating 70% of Customer Support With Agents (Without Being Awful)",
    excerpt:
      "A practical guide to building a tiered agent system that handles repeat questions, escalates the rest cleanly, and never lies to a customer.",
    difficulty: "advanced",
    incomeType: "hybrid",
    tags: ["agents", "support", "saas", "ops"],
    premium: true,
    featured: false,
    readMinutes: 18,
    views: 3812,
    likes: 162,
    author: author3,
    content: md([
      "## Tier 1 — knowledge base agent",
      "Scoped to your docs only. Refuses anything outside scope. Logs every refusal as a content gap.",
      "## Tier 2 — accounts agent",
      "Read-only on user data. Confirms identity before taking action. Has a list of allowed actions and nothing else.",
      "## Tier 3 — human",
      "The handoff message includes the full conversation, the agent's confidence level, and a one-line summary.",
    ]),
  },
  {
    slug: "passive-income-myths",
    categorySlug: "passive-income",
    title: "Five Passive Income Myths AI Did Not Fix",
    excerpt:
      "AI made many things faster. It did not make passive income passive. A grounded look at what 'passive' actually means in 2026.",
    difficulty: "beginner",
    incomeType: "passive",
    tags: ["mindset", "passive", "honest", "frameworks"],
    premium: false,
    featured: false,
    readMinutes: 6,
    views: 8930,
    likes: 401,
    author: author1,
    content: md([
      "## The myths",
      "- 'Set it and forget it' — the maintenance cost is real.",
      "- 'No skills needed' — the skills shifted; they didn't disappear.",
      "- 'Easy six figures' — possible, but the survivorship bias is enormous.",
      "- 'AI replaces taste' — it doesn't, and your taste is the moat.",
      "- 'You can skip the audience step' — you can't. You are still selling to people.",
    ]),
  },
  {
    slug: "notion-templates-with-gpt",
    categorySlug: "passive-income",
    title: "Notion Templates That Sell: The Embedded GPT Edge",
    excerpt:
      "Static Notion templates are saturated. Embedding a custom GPT gives you a wedge — and lets you charge ten times more for the same idea.",
    difficulty: "intermediate",
    incomeType: "passive",
    tags: ["notion", "templates", "gpts", "products"],
    premium: false,
    featured: false,
    readMinutes: 9,
    views: 5240,
    likes: 220,
    author: author4,
    content: md([
      "## The pattern",
      "Sell a Notion workspace plus a custom GPT trained on the workspace's logic. Buyers get a tool, not a doc.",
      "## What sells",
      "Operations templates for solo founders, content calendars for creators, OKR systems for tiny teams.",
      "## Pricing",
      "$49 for the template alone. $149 with the embedded GPT. Most buyers pick the bundle.",
    ]),
  },
];

const resources = [
  {
    title: "ChatGPT",
    description: "The everyday assistant. Worth a subscription if you write, code, or research.",
    url: "https://chat.openai.com",
    category: "ai-tools",
    pricing: "freemium",
    tags: ["chat", "writing", "research"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=chatgpt&backgroundColor=10a37f",
  },
  {
    title: "Claude",
    description: "Long-context model with thoughtful prose. Pairs well with research-heavy work.",
    url: "https://claude.ai",
    category: "ai-tools",
    pricing: "freemium",
    tags: ["chat", "research", "writing"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=claude&backgroundColor=ed7c43",
  },
  {
    title: "Cursor",
    description: "AI-native code editor. The cmd+K loop changed how we ship features.",
    url: "https://cursor.com",
    category: "ai-tools",
    pricing: "freemium",
    tags: ["code", "editor", "developers"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=cursor&backgroundColor=0a0a0a",
  },
  {
    title: "n8n",
    description: "Open-source workflow automation. Self-host it and never pay per task again.",
    url: "https://n8n.io",
    category: "automation",
    pricing: "freemium",
    tags: ["automation", "workflows", "self-host"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=n8n&backgroundColor=ea4b71",
  },
  {
    title: "Make",
    description: "Visual automation. Easier handoff to non-technical clients than n8n.",
    url: "https://make.com",
    category: "automation",
    pricing: "freemium",
    tags: ["automation", "visual", "client-friendly"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=make&backgroundColor=6d00cc",
  },
  {
    title: "Beehiiv",
    description: "Newsletter platform built for monetization. Sponsor marketplace included.",
    url: "https://beehiiv.com",
    category: "passive-income",
    pricing: "freemium",
    tags: ["newsletter", "media", "sponsorships"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=beehiiv&backgroundColor=fde047",
  },
  {
    title: "Gumroad",
    description: "Sell digital products in an afternoon. Templates, courses, AI prompts.",
    url: "https://gumroad.com",
    category: "passive-income",
    pricing: "free",
    tags: ["ecommerce", "digital-products"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=gumroad&backgroundColor=ff90e8",
  },
  {
    title: "Apollo.io",
    description: "B2B prospect data and outbound sequences. The cold email backbone.",
    url: "https://apollo.io",
    category: "freelancing",
    pricing: "freemium",
    tags: ["sales", "outbound", "prospecting"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=apollo&backgroundColor=2563eb",
  },
  {
    title: "ElevenLabs",
    description: "TTS voices that don't sound like a robot. Faceless YouTube essential.",
    url: "https://elevenlabs.io",
    category: "ai-tools",
    pricing: "freemium",
    tags: ["voice", "tts", "audio"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=eleven&backgroundColor=000000",
  },
  {
    title: "Descript",
    description: "Edit video like a doc. AI cleanup and clip generation built in.",
    url: "https://descript.com",
    category: "ai-tools",
    pricing: "freemium",
    tags: ["video", "podcast", "editing"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=descript&backgroundColor=4f46e5",
  },
  {
    title: "Notion",
    description: "Where your operations live. Pair with embedded GPTs for productized templates.",
    url: "https://notion.so",
    category: "passive-income",
    pricing: "freemium",
    tags: ["productivity", "templates"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=notion&backgroundColor=ffffff",
  },
  {
    title: "Stripe",
    description: "Payments that just work. Atlas + Tax bundles make global hustles feasible.",
    url: "https://stripe.com",
    category: "freelancing",
    pricing: "free",
    tags: ["payments", "infrastructure"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=stripe&backgroundColor=635bff",
  },
  {
    title: "Lex",
    description: "A quiet writing surface with AI on the side. Best for long-form drafting.",
    url: "https://lex.page",
    category: "ai-tools",
    pricing: "freemium",
    tags: ["writing", "drafting"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=lex&backgroundColor=f97316",
  },
  {
    title: "Granola",
    description: "Meeting notes that summarize what mattered, not what was said.",
    url: "https://granola.ai",
    category: "ai-tools",
    pricing: "freemium",
    tags: ["meetings", "notes"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=granola&backgroundColor=fcd34d",
  },
  {
    title: "Replit",
    description: "Build, deploy, and ship AI products from the browser.",
    url: "https://replit.com",
    category: "ai-tools",
    pricing: "freemium",
    tags: ["dev", "deploy", "agents"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=replit&backgroundColor=f26207",
  },
  {
    title: "Substack",
    description: "Newsletter + community in one. Built-in audience discovery.",
    url: "https://substack.com",
    category: "passive-income",
    pricing: "free",
    tags: ["newsletter", "community"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=substack&backgroundColor=ff6719",
  },
  {
    title: "Loom",
    description: "Async video walkthroughs. Crucial for outbound and client communication.",
    url: "https://loom.com",
    category: "freelancing",
    pricing: "freemium",
    tags: ["video", "async", "client"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=loom&backgroundColor=625df5",
  },
  {
    title: "Zapier",
    description: "The original automation glue. Best when you need integrations no one else has.",
    url: "https://zapier.com",
    category: "automation",
    pricing: "freemium",
    tags: ["automation", "integrations"],
    logo: "https://api.dicebear.com/9.x/icons/svg?seed=zapier&backgroundColor=ff4f00",
  },
];

async function main() {
  logger.info("Seeding database...");
  await db.delete(postsTable);
  await db.delete(categoriesTable);
  await db.delete(resourcesTable);

  const insertedCats = await db.insert(categoriesTable).values(categories).returning();
  const bySlug = new Map(insertedCats.map((c) => [c.slug, c.id] as const));

  const now = Date.now();
  await db.insert(postsTable).values(
    posts.map((p, i) => ({
      slug: p.slug,
      title: p.title,
      excerpt: p.excerpt,
      content: p.content,
      coverImage: cover(p.slug),
      categoryId: bySlug.get(p.categorySlug)!,
      difficulty: p.difficulty,
      incomeType: p.incomeType,
      tags: p.tags,
      premium: p.premium,
      featured: p.featured,
      readMinutes: p.readMinutes,
      views: p.views,
      likes: p.likes,
      authorName: p.author.name,
      authorRole: p.author.role,
      authorAvatar: p.author.avatar,
      publishedAt: new Date(now - i * 1000 * 60 * 60 * 36),
    })),
  );

  await db.insert(resourcesTable).values(resources);

  logger.info("Seed complete.");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    logger.error({ err }, "Seed failed");
    process.exit(1);
  });
